# What metrics to evaluate on
metrics:
  - mse
  - tcc
  - scc

# Batch size
batch_size: 10
domain_size: 5
domain_varying: true

# Learning rate and cosine annealing scheduler
gradient_clip: 10
learning_rate: 1e-3

# KL loss betas
betas:
  um: 3
  z0: 1e-2
  kl: 1e-3
