defaults:
  - _self_
  - model: feedforward-mask
  - dataset: pretrain
  - training: pretrain
  - memory: exact-replay

hydra:
  output_subdir: null
  run:
    dir: .

# PyTorch-Lightning hardware params
accelerator: gpu
devices: [0]
num_workers: 0

# Random seed of the run
seed: 1111

# Whether to set a specific experiment tag to differentiate or not
exptag: ""

gradual_percent: 1.0
limited_samples: 10

# Experiment folder naming
exptype: pretrain_${model.model}_${dataset.dataset}_${training.task_setting}_${memory.memory_name}_${seed}_${limited_samples}samples
model_path: ""
checkpt: ""

# Whether to save reconstructions to disk
save_files: true

# Whether we are training/testing and whether to regenerate metrics
train: true
generate: true

# What version to save to, default None
version: null

